version: 2

project_name: clickspectre

builds:
  - id: clickspectre
    main: ./cmd/clickspectre
    binary: clickspectre
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: "^feat(\\(.+\\))?:"
    - title: Bug Fixes
      regexp: "^fix(\\(.+\\))?:"
    - title: Performance
      regexp: "^perf(\\(.+\\))?:"
    - title: Refactoring
      regexp: "^refactor(\\(.+\\))?:"
    - title: Chores
      regexp: "^chore(\\(.+\\))?:"

brews:
  - name: clickspectre
    repository:
      owner: ppiankov
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ppiankov/clickspectre
    description: "ClickHouse usage analyzer — identifies unused tables, service dependencies, and cleanup recommendations"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "clickspectre"
    test: |
      assert_match "clickspectre", shell_output("#{bin}/clickspectre version")
