package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

// NewCIInitCmd creates the ci-init command.
func NewCIInitCmd() *cobra.Command {
	var (
		ciFormat string
		stage    string
	)

	cmd := &cobra.Command{
		Use:   "ci-init",
		Short: "Generate CI pipeline snippet for clickspectre",
		Long:  "Print a ready-to-paste CI job block to stdout. Supports GitLab CI and GitHub Actions.",
		RunE: func(cmd *cobra.Command, args []string) error {
			switch ciFormat {
			case "gitlab":
				cmd.Print(gitlabSnippet(stage))
			case "github":
				cmd.Print(githubSnippet())
			default:
				return fmt.Errorf("unsupported --format %q: use gitlab or github", ciFormat)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&ciFormat, "format", "gitlab", "CI format: gitlab, github")
	cmd.Flags().StringVar(&stage, "stage", "validate", "CI stage name (GitLab only)")

	return cmd
}

func gitlabSnippet(stage string) string {
	return fmt.Sprintf(`# Generated by clickspectre ci-init
# Paste into .gitlab-ci.yml
# Requires CLICKHOUSE_DSN set as a masked CI/CD variable

clickspectre:analyze:
  stage: %s
  image: ghcr.io/ppiankov/clickspectre:latest
  script:
    - clickspectre analyze
        --clickhouse-dsn "$CLICKHOUSE_DSN"
        --lookback 30d
        --format sarif
        --output ./report
  artifacts:
    paths:
      - report/report.sarif
    when: always
    expire_in: 7 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  allow_failure: false
`, stage)
}

func githubSnippet() string {
	return `# Generated by clickspectre ci-init
# Add to .github/workflows/clickspectre.yml
# Requires CLICKHOUSE_DSN set as a repository secret

name: ClickSpectre Analysis
on:
  pull_request:
  push:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clickspectre
        run: |
          curl -sSL https://github.com/ppiankov/clickspectre/releases/latest/download/clickspectre_linux_amd64.tar.gz | tar xz
          sudo mv clickspectre /usr/local/bin/

      - name: Run analysis
        env:
          CLICKHOUSE_DSN: ${{ secrets.CLICKHOUSE_DSN }}
        run: |
          clickspectre analyze \
            --clickhouse-dsn "$CLICKHOUSE_DSN" \
            --lookback 30d \
            --format sarif \
            --output ./report

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: report/report.sarif
`
}
